{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/pet (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1734603ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_add_pet","uid":"ccbbdb72fd91f76b","parentUid":"98785caa43ac30d34dca3348b7dae1f0","status":"broken","time":{"start":1737941894040,"stop":1737941894190,"duration":150},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"98785caa43ac30d34dca3348b7dae1f0"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/pet (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733e6e210>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_update_pet","uid":"6466c4702c1c41bc","parentUid":"240288e95f5c98ce7bee1c6da869638e","status":"broken","time":{"start":1737941894366,"stop":1737941894516,"duration":150},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"240288e95f5c98ce7bee1c6da869638e"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/pet/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f17355eda00>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_pet_by_id","uid":"82ffb92b8dadf46f","parentUid":"2262980282676f297c899b65db9fdbec","status":"broken","time":{"start":1737941894630,"stop":1737941894782,"duration":152},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"2262980282676f297c899b65db9fdbec"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/pet/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733e742f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_pet","uid":"2aa319a6e36f1c9f","parentUid":"d9a8362499abecb2a7ed3d89bb0f139b","status":"broken","time":{"start":1737941894893,"stop":1737941895040,"duration":147},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"d9a8362499abecb2a7ed3d89bb0f139b"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/pet/findByStatus?status=available (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733e76900>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_find_pets_by_status","uid":"413c637d880e566a","parentUid":"9836b561cbd2c2811d2484cbdb1cdbc6","status":"broken","time":{"start":1737941895147,"stop":1737941895295,"duration":148},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"9836b561cbd2c2811d2484cbdb1cdbc6"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/pet/findByTags?tags=tag1%2Ctag2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733e7cdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_find_pets_by_tags","uid":"d426936f00ba33dd","parentUid":"f82d8ec768540cf76ef0b660a84d52ed","status":"broken","time":{"start":1737941895404,"stop":1737941895556,"duration":152},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"f82d8ec768540cf76ef0b660a84d52ed"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/pet/1/uploadImage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733e7db20>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_upload_image","uid":"b0900e3c44b16752","parentUid":"ac44ededabac1584f2b3d6a6bc8a769e","status":"broken","time":{"start":1737941895667,"stop":1737941895813,"duration":146},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"ac44ededabac1584f2b3d6a6bc8a769e"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/store/order (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733e8e930>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_place_order","uid":"da09f1216a06dd00","parentUid":"0d5a64e83c3e9fba1c5640f9ad9b4395","status":"broken","time":{"start":1737941895929,"stop":1737941896082,"duration":153},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"0d5a64e83c3e9fba1c5640f9ad9b4395"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/store/order/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733e926c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_find_purchase_order_by_id","uid":"49074e8dcd79a34c","parentUid":"f61d93f13c2eca22148308ac0c1718b2","status":"broken","time":{"start":1737941896198,"stop":1737941896347,"duration":149},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"f61d93f13c2eca22148308ac0c1718b2"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/store/order/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733e92750>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_order","uid":"bc25934d6961c86b","parentUid":"967b181e22f7124a6fb495e999d55953","status":"broken","time":{"start":1737941896455,"stop":1737941896606,"duration":151},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"967b181e22f7124a6fb495e999d55953"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/store/inventory (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733e932f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_inventory","uid":"589fe60d446e968a","parentUid":"e78c2d754139475ac33f7fe2add6078f","status":"broken","time":{"start":1737941896716,"stop":1737941896864,"duration":148},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"e78c2d754139475ac33f7fe2add6078f"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/user/createWithArray (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f17345a8950>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_create_users_with_array","uid":"8678619d1bdd8d27","parentUid":"e77385b4c10268468963de50b925b906","status":"broken","time":{"start":1737941896971,"stop":1737941897122,"duration":151},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"e77385b4c10268468963de50b925b906"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/user/createWithList (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733ee5d00>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_create_users_with_list","uid":"e2e76ee2f89e23c","parentUid":"f2403b3a6c09710e7ea831954ff44985","status":"broken","time":{"start":1737941897229,"stop":1737941897377,"duration":148},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"f2403b3a6c09710e7ea831954ff44985"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/user/user1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733eece00>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_user_by_username","uid":"a29855a540176743","parentUid":"b01abbb5ed88a230d4af8926e735bf46","status":"broken","time":{"start":1737941897485,"stop":1737941897635,"duration":150},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"b01abbb5ed88a230d4af8926e735bf46"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/user/user1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733ed7ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_update_user","uid":"e23e6fcb589413f4","parentUid":"65e2984d4030f44c546733bb833d9b4c","status":"broken","time":{"start":1737941897743,"stop":1737941897892,"duration":149},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"65e2984d4030f44c546733bb833d9b4c"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/user/user1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733c211f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_user","uid":"f95741e03f136df0","parentUid":"64bbf169f54a93314238915aaad99b32","status":"broken","time":{"start":1737941898000,"stop":1737941898152,"duration":152},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"64bbf169f54a93314238915aaad99b32"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/user/login?username=user1&password=password1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733c23170>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_login_user","uid":"b6e86fd8a2a21e89","parentUid":"ef8f1c86dc3d2a9e0243c8578378ba07","status":"broken","time":{"start":1737941898258,"stop":1737941898402,"duration":144},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"ef8f1c86dc3d2a9e0243c8578378ba07"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/user/logout (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733ed5fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_logout_user","uid":"6a6926ad0c168e80","parentUid":"02028dd8bf89659a9a7f194dee39197a","status":"broken","time":{"start":1737941898524,"stop":1737941898671,"duration":147},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"02028dd8bf89659a9a7f194dee39197a"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='5.178.111.192', port=8081): Max retries exceeded with url: /v2/user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1733e918b0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_create_user","uid":"ad78dfc585aaca3e","parentUid":"1d00603078cee83f808ca762c2502be2","status":"broken","time":{"start":1737941898779,"stop":1737941898931,"duration":152},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"1d00603078cee83f808ca762c2502be2"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}